default: &default
  scrapping:
    base_url: "https://www.musicfestivalwizard.com/festivals/"
    additional_words: ["festival", "music festival"]
  spotify:
    app_id: "samhecquet"
production:
  <<: *default
test:
  <<: *default
development:
  <<: *default